### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by savy-91** [fayeed/flutter_freshchat#15]
Hi, I'm currently experiencing crashes on iOS. I am running the latest available version of the package from pub.dev and no errors on the android build of my app.

Here is the error I face whenever I try to show the FAQs:
```
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010feab1bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010f449735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010fec9e44 +[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x000000010feafed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x000000010feb1da8 _CF_forwarding_prep_0 + 120
	5   flutter_freshchat                   0x000000010e786638 -[FDWebImageDownloaderOperation URLSession:task:didCompleteWithError:] + 514
	6   flutter_freshchat                   0x000000010e7eb7f7 -[FDWebImageDownloader URLSession:task:didCompleteWithError:] + 113
	7   CFNetwork                           0x0000000112018342 __51-[NSURLSession delegate_task:did<…>
Lost connection to device.
```

Here is the code needed to replicate the error above:
 ```
initChat () async {
    await FlutterFreshchat.init(appID: '...', appKey: '...', cameraEnabled: false);
    //FreshchatUser user = FreshchatUser.initail();
    //user.firstName = appState.snapshot.customer.appUser.name;
    //user.lastName = appState.snapshot.customer.appUser.surname;
    //user.phone = appState.snapshot.customer.appUser.loginPhoneNumber;
    //user.email = appState.snapshot.customer.appUser.email;
    //await FlutterFreshchat.identifyUser(externalID: appState.snapshot.customer.appUser.id);
    //await FlutterFreshchat.updateUserInfo(user: user);
  }

  showChat() async {
    await FlutterFreshchat.showConversations(tags: const [], title: 'Chat di assistenza');
  }

  showFaq() async {
    await FlutterFreshchat.showFAQs(showContactUsOnAppBar: false, showContactUsOnFaqScreens: false, showFaqCategoriesAsGrid: false);
  }

  @override
  void dispose(){
    super.dispose();
    FlutterFreshchat.resetUser();
  }

  @override
  void initState() {
    super.initState();
    initChat();
  }
```
If I uncomment the remaining lines in initChat() then the app crashes earlier without writing any debug information in console. It crashes during the initChat() call.

The code as is is able to successfully open and run the chat but crashes with the FAQ page.

On Android, we are currently using the code without all the comments in initChat.

I was able to replicate it with a physical iPhone 6s on iOS 12.0.1 and on an emulated iPhone XR on iOS 12.1

Here is also the output from flutter doctor
```
[✓] Flutter (Channel stable, v1.9.1+hotfix.2, on Mac OS X 10.13.6 17G65, locale
    it-IT)
[✓] Xcode - develop for iOS and macOS (Xcode 10.1)
```

**Comment by fayeed** [comment]
@savy-91 the problem was caused in the `updateUserInfo` method where if the `custom_property_list` was not provided It would crash the app, just release a new version `1.2.1` that should fix the problem for you.

**Comment by savy-91** [comment]
Cool! I'll test it later today and let you know, thanks a lot

**Comment by savy-91** [comment]
I just tried and unfortunately it still crashes when I show the FAQs with the setup above

**Comment by fayeed** [comment]
@savy-91 I was testing the `showFAQs` method and it seems to be working when there are no FAQs configured. As I don't have a paid membership to freshchat I am not able to test with FAQs configured and I think you might be facing the problem something related to that.

Anyway I will keep this issue open so someone else can fix this or maybe I will.

**Comment by savy-91** [comment]
It never occurred again, I would say this can be closed. Thanks for the help!
