### ISSUE TITLE
The attachment icon isn't displayed on the iPhone

### ISSUE THREAD

**Issue by MaxiakaLimit** [fayeed/flutter_freshchat#27]
<img width="313" alt="1" src="https://user-images.githubusercontent.com/8420608/73928061-8ab33d80-48e3-11ea-88d3-96158f052a9f.png">

**Comment by chaitanya-y** [comment]
How to generate restoreId in flutter fresh chat(getting empty string)?

I checked some issues online.someone mentioned that restoreId will get generated only after first was sent.I tried to call send message function and then did identify user .Still, I am getting restoreId as empty string.

FreshchatUser user = FreshchatUser.initail();
user.email = email;
user.firstName = firstName;
user.lastName = lastName;
user.phoneCountryCode = '91';
user.phone = phone;
bool result = await FlutterFreshchat.updateUserInfo(user: user);
bool sendMessageSuccess =await FlutterFreshchat.send(message: 'Hello',tag: 'test');
if(sendMessageSuccess){
freshChatId = await FlutterFreshchat.identifyUser(externalID: phone, restoreID: null);
print('freshChatId');
}

and
2)Is there any way to trigger an event on the click of back button in the flutter chat screen.

**Comment by fayeed** [comment]
@MaxiakaLimit This has to do with Freshchat itself and not this package.

**Comment by naren7229** [comment]
I got the same issue its due to the build system in iOS 
works in local but doesn't load any icons
fails to build app for release

**Comment by thecoffeehog** [comment]
@fayeed How do you suggest we deal with this?

**Comment by fayeed** [comment]
As this is the problem with the IOS SDK itself you will have to wait for the Freshchat team to fix this problem, I would have submitted a PR but I don't know much about IOS dev.
You could create an issue on their repository asking to fix this.

Right now if its an option, you could disable the camera & gallery options while initializing the SDK this will remove the icon from there.

**Comment by thecoffeehog** [comment]
Thanks @fayeed for the quick response. I will raise this with Freshchat and let's see how quickly they take it up.

Also a big thank you for building this plugin :)

**Comment by thecoffeehog** [comment]
@fayeed The team at Freshchat wants to know which version of the SDK we are using, can you please confirm?

**Comment by naren7229** [comment]
> @fayeed The team at Freshchat wants to know which version of the SDK we are using, can you please confirm?

I think he is using 2.9.0

**Comment by fayeed** [comment]
I am using v2.9.0.

**Comment by thecoffeehog** [comment]
@fayeed Perfect! We have communicated the same to the Freshchat team.

**Comment by thecoffeehog** [comment]
https://github.com/freshdesk/freshchat-ios/issues/93#issuecomment-585572143

**Comment by tonuegbu** [comment]
> @fayeed, can you please have a look? : [freshdesk/freshchat-ios#93 (comment)](https://github.com/freshdesk/freshchat-ios/issues/93#issuecomment-585572143)

Would try this later to see if it fixes it. I don't recall deleting that bundle, however.

**Comment by thecoffeehog** [comment]
Sure, thanks @tonuegbu :)

**Comment by naren7229** [comment]
@tonuegbu I think its something to do with podspec

**Comment by nihalreddy33** [comment]
@thecoffeehog were you able to find a workaround for this issue?

**Comment by thecoffeehog** [comment]
No. I had to use it like that only.

**Comment by nihalreddy33** [comment]
@thecoffeehog the build isn't working when I do flutter build ios. Please let me know if there any solution for it.
/build/ios/Release-iphoneos/flutter_freshchat/flutter_freshchat.framework/freshchat_channels_image@3x.png
    Command /Applications/Xcode.app/Contents/Developer/usr/bin/copypng failed with exit code 1

**Comment by fayeed** [comment]
I have updated the package to `1.3.0` this should resolve this issue.

**Comment by nihalreddy33** [comment]
@fayeed we are still facing issues even after updating.
    <module-includes>:1:9: note: in file included from <module-includes>:1:
    #import "Headers/flutter_freshchat-umbrella.h"
            ^
  /ios/Pods/Target Support Files/flutter_freshchat/flutter_freshchat-umbrella.h:13:9: note: in file included from
    /ios/Pods/Target Support Files/flutter_freshchat/flutter_freshchat-umbrella.h:13:
    #import "FlutterFreshchatPlugin.h"
            ^
   /flutter/.pub-cache/hosted/pub.dartlang.org/flutter_freshchat-1.3.0/ios/Classes/FlutterFreshchatPlugin.h:2:9: error: include of
    non-modular header inside framework module 'flutter_freshchat.FlutterFreshchatPlugin':
    '/ios/Pods/FreshchatSDK/FreshchatSDK/FreshchatSDK.h'
    #import "FreshchatSDK.h"
            ^
    <unknown>:0: error: could not build Objective-C module 'flutter_freshchat'
    Command CompileSwift failed with a nonzero exit code
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
